//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BSTIntegrationExample.QXEnrollmentService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="benefitagent.com", ConfigurationName="QXEnrollmentService.IEnrollment")]
    public interface IEnrollment {
        
        [System.ServiceModel.OperationContractAttribute(Action="benefitagent.com/IEnrollment/GetLoginGUID", ReplyAction="benefitagent.com/IEnrollment/GetLoginGUIDResponse")]
        System.Guid GetLoginGUID(System.Guid portfolioID, System.Guid uniqueID);
        
        [System.ServiceModel.OperationContractAttribute(Action="benefitagent.com/IEnrollment/Query", ReplyAction="benefitagent.com/IEnrollment/QueryResponse")]
        string Query(string data);
        
        [System.ServiceModel.OperationContractAttribute(Action="benefitagent.com/IEnrollment/Upload", ReplyAction="benefitagent.com/IEnrollment/UploadResponse")]
        string Upload(string data);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IEnrollmentChannel : BSTIntegrationExample.QXEnrollmentService.IEnrollment, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class EnrollmentClient : System.ServiceModel.ClientBase<BSTIntegrationExample.QXEnrollmentService.IEnrollment>, BSTIntegrationExample.QXEnrollmentService.IEnrollment {
        
        public EnrollmentClient() {
        }
        
        public EnrollmentClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public EnrollmentClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EnrollmentClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EnrollmentClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Guid GetLoginGUID(System.Guid portfolioID, System.Guid uniqueID) {
            return base.Channel.GetLoginGUID(portfolioID, uniqueID);
        }
        
        public string Query(string data) {
            return base.Channel.Query(data);
        }
        
        public string Upload(string data) {
            return base.Channel.Upload(data);
        }
    }
}
